# Generated by Django 5.1.2 on 2025-05-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_category_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategoryaccess',
            unique_together=set(),
        ),
    ]
