# Generated by Django 5.1.2 on 2025-05-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_quizattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_questions',
        ),
    ]
