# Generated by Django 5.1.2 on 2025-05-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_answer_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='points_earned',
            new_name='score_earned',
        ),
    ]
