# Generated by Django 5.1.2 on 2025-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_points_earned_useranswer_score_earned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='current_question_index',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='score',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='total_questions',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='single', max_length=20),
        ),
    ]
