# Generated by Django 5.1.2 on 2025-06-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quizattempt_completed_at_quizattempt_correct_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='current_question_index',
        ),
    ]
