# Generated by Django 5.1.2 on 2025-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_quizattempt_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='skipped_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
