# Generated by Django 5.1.2 on 2025-07-04 21:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Explanation'),
            preserve_default=False,
        ),
    ]
