# Generated by Django 5.1.2 on 2025-08-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_answer_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='tournament_end_time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='tournament_start_time',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
