# Generated by Django 5.1.2 on 2025-08-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_quiz_difficulty_remove_quiz_quiz_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_pdfs/'),
        ),
    ]
