# Generated by Django 5.1.2 on 2025-08-05 09:03

import quiz.models.quiz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_quiz_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.quiz.unique_file_upload_path, validators=[quiz.models.quiz.validate_pdf]),
        ),
    ]
