# Generated by Django 5.1.2 on 2025-08-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_alter_quiz_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_answers',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
