# Generated by Django 5.1.2 on 2025-08-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_remove_useranswer_selected_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('g', 'G'), ('d', 'D')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answers',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('g', 'G'), ('d', 'D')], default=None, max_length=1),
        ),
    ]
