# Generated by Django 5.1.2 on 2025-08-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='is_skipped',
        ),
    ]
