# Generated by Django 5.1.2 on 2025-08-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_remove_useranswer_is_skipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='selected_answers',
            new_name='selected_answer',
        ),
    ]
