# Generated by Django 5.1.2 on 2025-08-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_rename_selected_answers_useranswer_selected_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='skipped_answers',
        ),
    ]
