# Generated by Django 5.1.2 on 2025-08-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_topic_question_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='link',
            new_name='url',
        ),
    ]
