# Generated by Django 5.1.2 on 2025-08-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Blogs'},
        ),
    ]
