# Generated by Django 5.1.2 on 2025-08-24 10:08

import django.db.models.deletion
import quiz.models.quiz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_preferences'),
        ('quiz', '0030_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ImageField(blank=True, null=True, upload_to=quiz.models.quiz.upload_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='quiz.quizattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_notes', to='authentication.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
