# Generated by Django 5.1.2 on 2025-08-24 10:19

import quiz.models.quiz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_blacknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacknote',
            name='note',
            field=models.ImageField(default=1, upload_to=quiz.models.quiz.upload_image),
            preserve_default=False,
        ),
    ]
