# Generated by Django 5.1.2 on 2025-09-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_alter_blacknote_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
    ]
