# Generated by Django 5.1.2 on 2025-09-03 12:25

import quiz.models.quiz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_remove_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.FileField(default=1, upload_to=quiz.models.quiz.unique_exp_upload_path, validators=[quiz.models.quiz.validate_pdf]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.FileField(default=1, upload_to=quiz.models.quiz.unique_file_upload_path, validators=[quiz.models.quiz.validate_pdf]),
            preserve_default=False,
        ),
    ]
