# Generated by Django 5.1.2 on 2025-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_quiz_explanation_alter_quiz_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
