# Generated by Django 5.2.7 on 2026-03-02 10:43

import django.db.models.deletion
import imitation_quiz.models.imitation_quiz
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_preferences'),
        ('quiz', '0035_alter_question_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImitationQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit', models.IntegerField(default=30)),
                ('file', models.FileField(upload_to=imitation_quiz.models.imitation_quiz.unique_file_upload_path, validators=[imitation_quiz.models.imitation_quiz.validate_pdf])),
                ('explanation', models.FileField(upload_to=imitation_quiz.models.imitation_quiz.unique_exp_upload_path, validators=[imitation_quiz.models.imitation_quiz.validate_pdf])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imitation_quizzes', to='quiz.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImitationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('g', 'G'), ('d', 'D')], max_length=1)),
                ('score', models.IntegerField(default=1)),
                ('order', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imitation_questions', to='quiz.topic')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='imitation_quiz.imitationquiz')),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ImitationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('geted_attempt', 'Geted Attempt'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imitation_attempts', to='authentication.user')),
                ('imitation_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='imitation_quiz.imitationquiz')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImitationUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('g', 'G'), ('d', 'D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_earned', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.IntegerField(default=0, help_text='Time taken to answer in seconds')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='imitation_quiz.imitationattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imitation_quiz.imitationquestion')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
