# Generated by Django 5.2.7 on 2026-03-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imitation_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imitationquestion',
            name='topic',
        ),
    ]
