# Generated by Django 5.2.7 on 2026-03-03 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation_quiz', '0002_remove_imitationquestion_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='imitationquiz',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The quiz will close after this time.', verbose_name='End Date and Time'),
        ),
        migrations.AddField(
            model_name='imitationquiz',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The quiz will become accessible from this time.', verbose_name='Start Date and Time'),
        ),
    ]
