# Generated by Django 5.2.7 on 2026-03-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation_quiz', '0003_imitationquiz_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imitationquiz',
            name='max_space',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
