# Generated by Django 5.2.7 on 2026-03-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation_quiz', '0004_imitationquiz_max_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='imitationquiz',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
