# Generated by Django 5.2.7 on 2026-03-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation_quiz', '0005_imitationquiz_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='imitationquiz',
            name='available_laptops',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
