# Generated by Django 5.2.7 on 2026-03-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imitation_quiz', '0006_imitationquiz_available_laptops'),
    ]

    operations = [
        migrations.AddField(
            model_name='imitationattempt',
            name='laptop_type',
            field=models.CharField(choices=[('my', 'my'), ('company', 'company')], default='my', max_length=10),
        ),
    ]
